name: dto
description: A package with dto objects, used in the mobile app 'Kazky dytynstva'
version: 1.0.0
homepage: https://kazky.net

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  json_annotation: 4.7.0
  equatable: 2.0.5

dev_dependencies:
  lints: 2.0.0
  build_runner: 2.2.1
  json_serializable: 6.4.1
  test: 1.21.6
