name: dto
description: A package with dto objects, used in the mobile app 'Kazky dytynstva'
version: 1.0.0
homepage: https://kazky.net

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  json_annotation: 4.8.0
  equatable: 2.0.5

dev_dependencies:
  lints: 2.0.0
  build_runner: 2.3.3
  json_serializable: 6.6.1
  test: 1.22.2
